name: Lint

on: [push, pull_request]

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Python dependencies
        run: pip install black flake8 isort

      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          black: true
          black_args: "--check --diff"
          flake8: true

      - name: Run isort on python files
        uses: isort/isort-action@master
        with:
          requirementsFiles: "scraper/pyproject.toml"
